[green_agent]
agentbeats_id = "019c0003-1c24-7320-8aa7-61e45ddc24fa"
env = { GOOGLE_MAPS_API_KEY = "${GOOGLE_MAPS_API_KEY}" }

[[participants]]
agentbeats_id = ""
name = "navigator"
env = { }

[config]
domain = "spatial_navigation"
num_tasks = 10
